"""Create a replay-based agent from a recorded episode.

Usage: py -3.12 harness/replay_agent.py <episode_id> <seat>

Reads the replay JSON, extracts all 720 actions for the given seat,
and generates a bot file that replays them verbatim.
"""
import json
import sys
import os

episode_id = sys.argv[1]
seat = int(sys.argv[2]) if len(sys.argv) > 2 else 0

# Find the replay file
import glob
files = glob.glob(f"replays/iter*/episode-{episode_id}-replay.json")
if not files:
    print(f"ERROR: No replay found for episode {episode_id}")
    sys.exit(1)

path = files[0]
d = json.load(open(path))
names = d["info"]["TeamNames"]
print(f"Replay: {path}")
print(f"Players: {names}")
print(f"Extracting actions for seat {seat} ({names[seat]})")

steps = d["steps"]
actions = []
for i, s in enumerate(steps):
    a = s[seat].get("action") or {}
    actions.append(a)

# Generate the bot file
bot_code = f'''"""
Replay agent: {names[seat]} from episode {episode_id}
Generated by harness/replay_agent.py

VERBATIM replay of {names[seat]}'s 720-turn action history.
This is the strongest economy we have identified.
"""

import json

ACTIONS = {json.dumps(actions, indent=2)}

_action_idx = [0]

def agent(obs):
    try:
        my_seat = obs["player"]
        day = obs["day"]
        hour = obs.get("hour", 0)
        turn = day * 24 + hour
        
        if turn < len(ACTIONS) and _action_idx[0] < len(ACTIONS):
            a = ACTIONS[_action_idx[0]]
            _action_idx[0] += 1
        else:
            a = ACTIONS[-1]  # last action if we run out
        
        # Convert action to our format
        market = a.get("market", [])
        farmer = a.get("farmer", ["PASS"])
        hands = a.get("hands", [])
        units = a.get("units", [])
        
        result = {{
            "farmer": farmer if farmer else ["PASS"],
            "hands": hands if hands else [],
            "market": market if market else []
        }}
        
        return result
    except Exception:
        return {{"farmer": ["PASS"], "hands": [], "market": []}}

# Reset on new episode
def reset():
    _action_idx[0] = 0

reset = reset
'''

out_path = f"bots/replay_{episode_id}_{seat}.py"
with open(out_path, "w", encoding="utf-8") as f:
    f.write(bot_code)

print(f"\nBot saved to {out_path}")
print(f"Total actions: {len(actions)}")
